# Generated by Django 4.0 on 2022-01-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_application_companylogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='status_note',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
